services:
  shinobi-sql:
    image: mysql:5.7
    volumes:
      - sql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ccio
      MYSQL_USER: majesticflame
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    restart: unless-stopped
    secrets:
      - db_root_password
      - db_password

  shinobi:
# Once the registry image is updated with the changes to entrypoint.sh,
# remove the build entry and use image instead.
#    image: registry.gitlab.com/shinobi-systems/shinobi:dev
    build:
      context: .
      args:
        SHINOBI_BRANCH: dev
    depends_on:
        - "shinobi-sql"
    volumes:
      - streams:/dev/shm/streams
      - home:/home/Shinobi
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - HOME=/home/Shinobi
      - DB_HOST=shinobi-sql
      - DB_USER=majesticflame
      - DB_DATABASE=ccio
      - SHINOBI_UPDATE=false
    restart: unless-stopped
    secrets:
      - db_password

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
  sql:
  streams:
  home: